"""new fields in user model

Revision ID: 83639130520a
Revises: 8b1d64e3b686
Create Date: 2019-12-13 12:41:34.450158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83639130520a'
down_revision = '8b1d64e3b686'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
